### ISSUE TITLE
Use individual lodash packages

### ISSUE THREAD

**Issue by simondel** [storybookjs/telejson#34]
Right now, the entire lodash package is downloaded with telejson, this can be optimized to the https://www.npmjs.com/package/lodash.get and https://www.npmjs.com/package/lodash.transform packages. These are also maintained by the lodash maintainers.

Keep in mind that you'll also have to update your `@types` dependency accordingly.

**Comment by Stephanemw** [comment]
Please use the tree-shakeable version instead - any lodash packages with the form lodash.xxxx are seriously old and full of vulnerabilities. lodash.get was last published 3 years ago (it's at version 4.4.2, as opposed to the maintained ones at v 4.17.15).

The use of https://www.npmjs.com/package/lodash is perfectly fine as long as you only import what you need.

Instead of ```const _ = require("lodash"); _.get(xxx);``` use the shakeable form ```const get = require("lodash/get");```

**Comment by simondel** [comment]
Fair enough!
